---

# Install nginx

- name: Install EPEL repo
  yum:
    name: epel-release

- name: Install nginx
  yum:
    name: "nginx-{{ nginx_ver }}"
    update_cache: yes
  notify:
    - Start and enable nginx service
