---

- name: Start and enable nginx service
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes

- name: Start and enable keepalived service
  become: yes
  service:
    name: keepalived
    state: started
    enabled: yes

- name: Reload nginx service
  become: yes
  service:
    name: nginx
    state: reloaded

- name: Applying settings for sysctl
  become: yes
  shell:
    cmd: sysctl --system
