---
# handlers file for nginx_deploy

- name: Start and enable nginx service
  become: yes
  service:
    name: nginx
    state: started
    enabled: yes
    
- name: Reload nginx service
  become: yes
  service:
    name: nginx
    state: reloaded
